// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace OvrlCoreTags
{
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(EnemyKilled);
};

namespace OvrlAbilityTags
{
	// Declare all of the custom native tags that Overlink will use
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActivateFail_IsDead);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActivateFail_Cooldown);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActivateFail_Cost);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActivateFail_TagsBlocked);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActivateFail_TagsMissing);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActivateFail_ActivationGroup);
};

namespace OvrlLocomotionModeTags
{
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InAir);
};

namespace OvrlGaitTags
{
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walking);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Running);
};

namespace OvrlLocomotionActionTags
{
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mantling); // Grab a high edge and pull up
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Vaulting); // Jump either over or on an obstacle
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ragdolling);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sliding);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WallrunningVertical);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WallrunningLeft);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WallrunningRight);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GettingUp);
};

namespace OvrlViewModeTags
{
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ADS);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Relaxed);
}

namespace OvrlInputTags
{
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Run);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Look_Mouse);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouch);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slide);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Jump);
};

namespace OvrlStanceTags
{
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Standing);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouching);
};

namespace OvrlOverlayModeTags
{
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Default);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pistol);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rifle);
};

namespace OvrlWeaponTags
{
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fire);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FireAuto);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Reload);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ReloadCompleted);

	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MagazineAmmo);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MagazineSize);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SpareAmmo);
}

namespace OvrlCheatTags
{
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GodMode);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UnlimitedHealth);
};

namespace OvrlUILayerTags
{
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerGame);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerMenu);
};