// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace OBM_AbilityTags
{
	// Declare all of the custom native tags that Overlink will use
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActivateFail_IsDead);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActivateFail_Cooldown);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActivateFail_Cost);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActivateFail_TagsBlocked);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActivateFail_TagsMissing);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActivateFail_ActivationGroup);
};

namespace OBM_LocomotionModeTags
{
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InAir);
};

namespace OBM_GaitTags
{
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walking);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Running);
};

namespace OBM_LocomotionActionTags
{
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mantling);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Vaulting);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ragdolling);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GettingUp);
};

namespace OBM_InputTags
{
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Look_Mouse);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouch);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Jump);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ADS);
};

namespace OBM_StanceTags
{
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Standing);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouching);
};

namespace OBM_OverlayModeTags
{
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Default);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pistol);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rifle);
};

namespace OBM_WeaponTags
{
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fire);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Reload);

	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MagazineAmmo);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MagazineSize);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SpareAmmo);
}

namespace OBM_CheatTags
{
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GodMode);
	OVERLINK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UnlimitedHealth);
};
